name: Linux test

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn global add @angular/cli karma lerna surge
    - run: yarn --frozen-lockfile
    - run: yarn build:ci
    - name: Run headless test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test:ci
    - run: yarn lerna run --scope altair-app webdriver-update-ci;
    - name: Run headless e2e test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn lerna run --scope altair-app e2e:ci
