name: PR

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn global add @angular/cli karma lerna surge
    - run: yarn --frozen-lockfile
    - run: yarn build:ci
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: yarn test:ci
    - run: yarn lerna run --scope altair-app webdriver-update-ci;
    - name: Run headless e2e test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: yarn lerna run --scope altair-app e2e:ci
  
  # https://github.com/marketplace/actions/deployment-action
  deploy-surge:
    runs-on: ubuntu-latest
    env:
      SURGE_URL: ${{ github.sha }}-${{ github.repository_owner }}-altair.surge.sh
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: yarn --frozen-lockfile
    - run: yarn build:ci
    - name: Deploy to surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: '${{ env.SURGE_URL }}'
        project: './packages/altair-app/dist'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}
