name: Release

# TODO: change
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  electron:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn global add @angular/cli karma lerna surge
    - run: yarn --frozen-lockfile
    - run: yarn build-electron
