name: Release

on:
  push:
    tags:
    - '**'

# TODO: Handle npm package release
# https://github.com/apollo-elements/apollo-elements/blob/6e1bb2ab51a60cebbaed2c8aca86b2e8b2ec9336/.github/workflows/main.yml#L25
# TODO: Handle browser extension release
jobs:
  release-draft:
    name: Release draft
    runs-on: ubuntu-latest
    steps:
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.github_token }}
        prerelease: false
        draft: true
  electron:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [12.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn global add @angular/cli karma lerna surge
    - run: yarn --frozen-lockfile
    - uses: nick-invision/retry@v2
      with:
        timeout_minutes: 15
        max_attempts: 3
        command: yarn lerna bootstrap
    - name: Install Snapcraft
      uses: samuelmeuli/action-snapcraft@v1
      if: startsWith(matrix.os, 'ubuntu')
      with:
        snapcraft_token: ${{ secrets.snap_store_login }}
    - name: Prepare for app notarization
      if: startsWith(matrix.os, 'macos')
      # Import Apple API key for app notarization on macOS
      run: |
        mkdir -p ~/private_keys/
        echo '${{ secrets.apple_api_key }}' > ~/private_keys/AuthKey_${{ secrets.apple_api_key_id }}.p8
    - name: Build/release Electron app
      uses: CryogenicPlanet/action-electron-builder@v2 # Using CryogenicPlanet until the main action adds skip_install
      with:
        github_token: ${{ secrets.github_token }}
        package_root: packages/altair-electron/
        skip_build: true
        skip_install: true
        mac_certs: ${{ secrets.mac_certs }}
        mac_certs_password: ${{ secrets.mac_certs_password }}
        args: '--publish always'
        max_attempts: 3
      env:
        # macOS notarization API key
        API_KEY_ID: ${{ secrets.apple_api_key_id }}
        API_KEY_ISSUER_ID: ${{ secrets.apple_api_key_issuer_id }}
  npm-publish:
    runs-on: ubuntu-latest
    needs: electron
    steps:
    - uses: actions/checkout@v2
    - name: Authenticate with Registry
      run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: yarn --frozen-lockfile
    - uses: nick-invision/retry@v2
      with:
        timeout_minutes: 15
        max_attempts: 3
        command: yarn build:ci
    - run: yarn lerna publish from-git --force-publish=* --no-git-tag-version --no-push --yes
